# Generated by Django 4.1.7 on 2023-03-13 03:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('category', models.CharField(blank=True, choices=[('carnes', 'Carnes'), ('picaditas', 'Picaditas'), ('postres', 'Postres'), ('bebidasalcohol', 'Bebidas con Alcohol'), ('bebidasinalcohol', 'Bebidas sin Alcohol')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countPeople', models.IntegerField(blank=True, default=1)),
                ('phoneContact', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, choices=[('Carta', 'Carta'), ('Elegir Menu', 'Elegir Menu')], max_length=16)),
                ('dateBooking', models.DateField(default=django.utils.timezone.now)),
                ('hourBooking', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client')),
            ],
        ),
    ]
