# Generated by Django 5.0.3 on 2024-03-20 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrera_recorrido'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
