# Generated by Django 5.0.3 on 2024-03-20 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrera_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='facultad',
            name='siglas',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultad',
            name='ubicacion',
            field=models.URLField(blank=True),
        ),
    ]
