# Generated by Django 5.0.3 on 2024-03-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facultad_date_joined_facultad_siglas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='fotos',
        ),
        migrations.AddField(
            model_name='bloque',
            name='imagen',
            field=models.ImageField(default=0, upload_to='media/bloque_fotos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
