# Generated by Django 5.0.3 on 2024-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bloque_fotos_bloque_imagen_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo_identificativo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
