# Generated by Django 5.0.3 on 2024-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carrera_codigo_identificativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='codigo_identificativo',
        ),
        migrations.AddField(
            model_name='bloque',
            name='codigo_identificativo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
